#!/usr/bin/env bash
# Prints the manual steps to complete after bootstrap.sh finishes.

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║            Post-Bootstrap Manual Steps (~10 min)         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C \"your-personal-email\""
echo "   cat ~/.ssh/id_ed25519.pub | pbcopy"
echo "   → Open Safari, paste into github.com → Settings → SSH Keys"
echo ""
echo "2. Set git identity:"
echo "   git config --global user.email \"your-personal-email\""
echo ""
echo "3. Switch dotfiles remote to SSH:"
echo "   cd ~/.dotfiles"
echo "   git remote set-url origin git@github.com:alexong7/dotfiles.git"
echo ""
echo "4. Clone Obsidian vault:"
echo "   mkdir -p ~/Documents"
echo "   cd ~/Documents"
echo "   git clone git@github.com:alexong7/Obsidian-Notes.git \"Obsidian Notes/Obsidian Notes\""
echo ""
echo "5. Install VS Code extensions (one-time):"
echo "   Run: ~/.dotfiles/install-vscode-extensions.sh"
echo ""
echo "6. Sign into apps:"
echo "   - VS Code (GitHub account for Settings Sync)"
echo "   - Obsidian (open vault at ~/Documents/Obsidian Notes/Obsidian Notes/Vault)"
echo "   - Claude Code (run 'claude' in terminal to authenticate)"
echo ""
echo "7. Open WezTerm — close Terminal.app forever."
echo ""
echo "Done! 🎉"
